spring:
  #  mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  app名称
  application:
    name: demo-handTemplate

  # thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML

  resources:
    static-locations: classpath:/static/

# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#  config-location: classpath:mybatis-config.xml

# 日志
#logging:
#  level:
#    root: warn