server:
  port: 10012
spring:
  application:
    name: shop-service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.202:3306/hm_shop
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/